import streamlit as st
import pandas as pd
import numpy as np

st.title("Isom 3400 Final Revision)
st.header()
st.subheader()
st.file_uploader()
st.write()
st.markdown()
st.tabs()
st.columns()
st.table()
st.data_editor()
st.dataframe()
st.write()
st.selectbox()
st.text_input()
st.number_input()
st.success()
st.button()
st.form()
st.bar_chart()
st.form_submit_button()
option_menu(menu_title= “”, options= [], icons=[], default_index=0)
